# Generated by Django 5.0.3 on 2024-04-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('position', models.CharField(max_length=30)),
                ('blood_g', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
